// Music Player
export const REQUEST_NEW_SONG = 'REQUEST_NEW_SONG';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SKIP_FORWARD = 'SKIP_FORWARD';
export const SKIP_BACKWARD = 'SKIP_BACKWARD';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const TOGGLE_LOOP = 'TOGGLE_LOOP';
export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const UPDATE_PLAYLIST_POSITION = 'UPDATE_PLAYLIST_POSITION';
export const HANDLE_PLAY_ERROR = 'HANDLE_PLAY_ERROR';
export const TOGGLE_QUEUE_DISPLAY = 'TOGGLE_QUEUE_DISPLAY';

// Library
export const UPDATE_LIBRARY_SONGS = 'UPDATE_LIBRARY_SONGS';
export const UPDATE_ALBUMS = 'UPDATE_ALBUMS';
export const UPDATE_ALBUM = 'UPDATE_ALBUM';
