// Music Player
export const PLAY_NEW_SONG = 'PLAY_NEW_SONG';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SKIP_FORWARD = 'SKIP_FORWARD';
export const SKIP_BACKWARD = 'SKIP_BACKWARD';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const TOGGLE_LOOP = 'TOGGLE_LOOP';
export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const UPDATE_PLAYLIST_POSITION = 'UPDATE_PLAYLIST_POSITION';

// Library
export const UPDATE_LIBRARY_SONGS = 'UPDATE_LIBRARY_SONGS';
